log-level: silent
allow-lan: true
redir-port: 1080
tproxy-port: 1081
ipv6: false
mode: rule
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: false
external-controller: 0.0.0.0:9090
external-ui: zashboard
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
profile:
  store-selected: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]

proxy-groups:
  - name: Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
    type: url-test
    url: http://www.msftncsi.com/ncsi.txt
    interval: 600
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Available_1.png
    include-all: true
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦

  - name: YouTube
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Discord
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Twitch
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitch.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: ĞšĞ¸Ğ½Ğ¾Ñ‚ĞµĞ°Ñ‚Ñ€Ñ‹
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/kino.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Meta
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/meta.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Spotify
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Telegram
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Community
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/community.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Cloudflare
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - PASS
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: AI
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bot.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Twitter
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Twitter.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: TikTok
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/tiktok.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Roblox
    type: select
    icon: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/group-icons/roblox.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: PlayStation
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: Nintendo
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: OTHERS
    type: select
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Other.png
    use:
      - subscription
    exclude-filter: ğŸ‡·ğŸ‡º|ğŸ‡°ğŸ‡¿|ğŸ‡ºğŸ‡¦
    proxies:
      - Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
      - DIRECT

  - name: QUIC
    type: select
    icon: https://github.com/zxc-rv/assets/raw/refs/heads/main/group-icons/quic.png
    proxies:
      - REJECT
      - PASS

# ĞŸĞ¾Ğ´ĞºĞ»ÑÑ‡ĞµĞ½Ğ¸Ğµ Ñ Ğ¸ÑĞ¿Ğ¾Ğ»ÑŒĞ·Ğ¾Ğ²Ğ°Ğ½Ğ¸ĞµĞ¼ Ğ¿Ğ¾Ğ´Ğ¿Ğ¸ÑĞºĞ¸
proxy-providers:
  subscription:
    type: http
    url: https://real.net-problemi.ru:7443/sub/dXNfODMzOTgsMTc1NDQwMzg4Mw9cJWVMLLSh#  <------------ Ğ—Ğ”Ğ•Ğ¡Ğ¬ Ğ’Ğ¡Ğ¢ĞĞ’Ğ˜Ğ¢Ğ¬ Ğ¡Ğ¡Ğ«Ğ›ĞšĞ£ ĞĞ Ğ’ĞĞ¨Ğ£ ĞŸĞĞ”ĞŸĞ˜Ğ¡ĞšĞ£
    path: ./proxy-providers/subscription.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.msftncsi.com/ncsi.txt
      interval: 120

rule-providers:
  refilter-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/domain-rule.mrs
    path: ./rule-providers/refilter-domains.mrs
    interval: 86400

  refilter-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/ip-rule.mrs
    path: ./rule-providers/refilter-ips.mrs
    interval: 86400

  kino:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/rules/kino.mrs
    path: ./rule-providers/kino-domains.mrs
    interval: 86400

  patreon:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/patreon.mrs
    path: ./rule-providers/patreon-domains.mrs
    interval: 86400

  roblox:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/roblox.mrs
    path: ./rule-providers/roblox-domains.mrs
    interval: 86400

  roblox-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/amatol/xkeen-configuration/raw/refs/heads/main/rules/roblox-ips.mrs
    path: ./rule-providers/roblox-ips.mrs
    interval: 86400

  tiktok:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs
    path: ./rule-providers/tiktok-domains.mrs
    interval: 86400

  playstation:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/playstation.mrs
    path: ./rule-providers/playstation-domains.mrs
    interval: 86400

  nintendo:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/nintendo.mrs
    path: ./rule-providers/nintendo-domains.mrs
    interval: 86400

  community:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/community.mrs
    path: ./rule-providers/community-domains.mrs
    interval: 86400

  cloudflare-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cloudflare.mrs
    path: ./rule-providers/cloudflare-ips.mrs
    interval: 86400

  discord:
    type: inline
    behavior: classical
    format: text
    payload:
      - AND,((DOMAIN-KEYWORD,discord),(NOT,((DOMAIN-SUFFIX,ru))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,TCP),(OR,((DST-PORT,2000-2300),(DST-PORT,8443))))
      - AND,((RULE-SET,cloudflare-ips,no-resolve),(NETWORK,UDP),(OR,((DST-PORT,19200-19400),(DST-PORT,50000-51000))))
      - AND,((IP-CIDR,5.200.14.128/25,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.0.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,34.2.0.0/15,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,35.192.0.0/11,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,66.22.192.0/18,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))
      - AND,((IP-CIDR,138.128.136.0/21,no-resolve),(NETWORK,UDP),(DST-PORT,50000-51000))

  telegram-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs
    path: ./rule-providers/telegram-ips.mrs
    interval: 86400

  meta-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://github.com/zxc-rv/assets/raw/refs/heads/main/rules/meta-ips.mrs
    path: ./rule-providers/meta-ips.mrs
    interval: 86400

  refilter-noech:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/re-filter-noech.mrs
    path: ./rule-providers/refilter-noech.mrs
    interval: 86400

  refilter-ech:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/re-filter/re-filter-ech.mrs
    path: ./rule-providers/refilter-ech.mrs
    interval: 86400

  torrent-trackers:
    type: http
    behavior: domain
    format: mrs
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-trackers.mrs
    path: ./rule-providers/torrent-trackers.mrs

  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://github.com/legiz-ru/mihomo-rule-sets/raw/main/other/torrent-clients.yaml
    path: ./rule-providers/torrent-clients.yaml
    interval: 86400

  AI-custom:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/AI.yaml
    path: ./rule-providers/ai-custom.yaml
    interval: 86400

  others:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/Ivan-Stepalin/xkeen-config-mihomo/main/rules/others.yaml
    path: ./rule-providers/others.yaml
    interval: 86400

rules:
  - AND,((DST-PORT,443),(NETWORK,UDP)),QUIC
  - OR,((DOMAIN-SUFFIX,gql.twitch.tv),(DOMAIN-SUFFIX,usher.ttvnw.net)),Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚ # Ğ Ğ°Ğ·Ğ±Ğ»Ğ¾ĞºĞ¸Ñ€Ğ¾Ğ²ĞºĞ° Ğ²Ñ‹ÑĞ¾ĞºĞ¾Ğ³Ğ¾ ĞºĞ°Ñ‡ĞµÑÑ‚Ğ²Ğ° Ğ½Ğ° Twitch.tv
  - GEOSITE,category-ai-!cn,AI
  - RULE-SET,AI-custom,AI
  - GEOSITE,spotify,Spotify
  - OR,((GEOSITE,youtube),(DOMAIN-SUFFIX,googleusercontent.com)),YouTube
  - GEOSITE,twitch,Twitch
  - GEOSITE,twitter,Twitter
  - RULE-SET,discord,Discord
  - OR,((GEOSITE,meta),(RULE-SET,meta-ips,no-resolve)),Meta
  - OR,((GEOSITE,telegram),(RULE-SET,telegram-ips,no-resolve)),Telegram
  - OR,((GEOSITE,cloudflare),(RULE-SET,cloudflare-ips)),Cloudflare
  - RULE-SET,kino,ĞšĞ¸Ğ½Ğ¾Ñ‚ĞµĞ°Ñ‚Ñ€Ñ‹
  - RULE-SET,community,Community
  - RULE-SET,tiktok,TikTok
  - RULE-SET,patreon,Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
  - RULE-SET,roblox,Roblox
  - RULE-SET,roblox-ips,Roblox
  - RULE-SET,playstation,PlayStation
  - RULE-SET,nintendo,Nintendo
  - RULE-SET,others,OTHERS
  - RULE-SET,refilter-domains,Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
  - RULE-SET,refilter-ips,Ğ¡Ğ²Ğ¾Ğ±Ğ¾Ğ´Ğ½Ñ‹Ğ¹ Ğ¸Ğ½Ñ‚ĞµÑ€Ğ½ĞµÑ‚
  - RULE-SET,torrent-clients,DIRECT
  - RULE-SET,torrent-trackers,DIRECT
  - MATCH,DIRECT
